In [1]:
import numpy as np

In [2]:
my_list= [1, 2, 3, 4]

In [3]:
np.array(my_list)

array([1, 2, 3, 4])

In [4]:
my_mat= [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [5]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
np.arange(0, 15, 3)

array([ 0,  3,  6,  9, 12])

In [7]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [8]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [9]:
np.linspace(0, 5, 10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [10]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [38]:
np.random.rand(4, 5)

array([[0.41082951, 0.01155411, 0.17703396, 0.24263557, 0.9869536 ],
       [0.35955469, 0.19943445, 0.56299584, 0.73725654, 0.48867508],
       [0.74069517, 0.88975668, 0.70195133, 0.49441424, 0.0191358 ],
       [0.36376758, 0.65545857, 0.60916735, 0.23505546, 0.75062801]])

In [40]:
np.random.randn(5)

array([-0.54899434,  0.99154073, -0.18450507, -0.38077569,  0.02767549])

In [42]:
arr= np.random.randint(1, 100, 5)

In [44]:
my_arr= np.arange(25)

In [46]:
my_arr.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [50]:
arri= np.random.randint(1, 50, 5)

In [52]:
new= np.arange(0, 11)

In [54]:
new

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [56]:
new[2]

2

In [58]:
new[3:5]

array([3, 4])

In [60]:
new[:-3]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [62]:
new[6:]

array([ 6,  7,  8,  9, 10])

In [74]:
arr_2= np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])

In [76]:
arr_2

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [90]:
arr_2[:2][1:]

array([[20, 25, 30]])

In [92]:
num= np.arange(1, 11)

In [98]:
bo= num >5

In [100]:
bo

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [108]:
num[bo== False]

array([1, 2, 3, 4, 5])

In [110]:
num[num <3]

array([1, 2])

In [120]:
myarr= np.arange(50)

In [130]:
myarr= myarr.reshape(5, 10)

In [134]:
myarr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [132]:
myarr[1:3, 3:5]

array([[13, 14],
       [23, 24]])

In [136]:
myarr[2:,5:9] 

array([[25, 26, 27, 28],
       [35, 36, 37, 38],
       [45, 46, 47, 48]])

In [142]:
myarr*myarr

array([[   0,    1,    4,    9,   16,   25,   36,   49,   64,   81],
       [ 100,  121,  144,  169,  196,  225,  256,  289,  324,  361],
       [ 400,  441,  484,  529,  576,  625,  676,  729,  784,  841],
       [ 900,  961, 1024, 1089, 1156, 1225, 1296, 1369, 1444, 1521],
       [1600, 1681, 1764, 1849, 1936, 2025, 2116, 2209, 2304, 2401]])

In [148]:
myarr/myarr

C:\Users\fatem\AppData\Local\Temp\ipykernel_16440\493219060.py:1: RuntimeWarning: invalid value encountered in divide
  myarr/myarr


array([[nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]])

In [162]:
me= np.arange(-3, -1)

In [164]:
np.abs(me)

array([3, 2])